### ISSUE TITLE
Identifo Configuration: Error loop in reading the configuration

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#233]
In Identifo v2.1.2, when the Identifo container is spinning up with an AWS IAM user, it use to get the configurations and parse them from S3 using this key in the config YAML file:
```
config:
    type: s3
    s3:
        region: ap-southeast-2
        bucket: identifo-dev
        key: server-config.yaml
```

But in v2.1.3 this config has been removed from "parser" but the application is expecting to get this piece of the configuration parsed properly. Please see the below code that is checking for that config:

![image](https://user-images.githubusercontent.com/8931595/134830642-ec5c71da-4c29-4674-9b2f-5e788ffaa061.png)
